ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.liquidity_trap]
path = "out/LiquidityTrap.sol/LiquidityTrap.json"
response_contract = "0x373FbBB0974dbD7057318E155aA0821219E734d3" 
response_function = "respondCallback(uint256)" 
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x9CE3efcDbBd57Aa5Df8938aB2e15AF4fea7f1029"]
